title = "The World Turns To Ash In My Mouth"
slug = "ash"
date = 2024-09-12

content = """
The world turns to ash in my mouth.  
All colors have gone gray  
and sound detunes to static.  


Days are a child's porridge  
lifted in a shallow spoon  
it flirts with the mouth  
and splatters back into the bowl


and lifts  
and flirts  
and falls  
 

and lifts, and flirts, and falls.  


Perhaps if I misbehave  
you'll send me to bed  
without my supper. 
"""